version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: auth
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    image: ahmedmohamedshalaby/node-app
    depends_on: 
      - db
    ports: 
      - '3000:3000'
