version: '3.1'

services:

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:  
      - "3308:3306"
    container_name: sqldb
    networks: 
      - backend

  web:
    image: iot_middleware
    depends_on: 
      - db
    ports: 
      - "3000:3000"
    links:
      - db
    networks: 
      - backend
  
  
networks:
  backend:
      

